# cores/pcsx_rearmed.cmake — libretro-pcsx_rearmed (PlayStation) core build.
#
# pcsx_rearmed is the long-time PSX core for ARM Switch homebrew because it
# ships a NEON / aarch64 dynamic recompiler (ari64 / new_dynarec). This
# recipe mirrors upstream Makefile.libretro's `platform=libnx` target plus
# the Makefile's ari64 + BUILTIN_GPU=neon source list.
#
#   - DYNAREC  = ari64                 -> libpcsxcore/new_dynarec/* +
#                                         linkage_arm64.S
#   - GPU       = gpulib + gpu_neon    -> psx_gpu_simd.c (intrinsics path,
#                                         not the ARM32-only .S)
#   - CHD       = libchdr + lzma + zstd (ChdRom support is what makes this
#                 the "go-to" PSX core for collections; mgba/melonds/etc
#                 don't pull this in).
#   - libchdr's vendored zlib is bypassed; we link devkitPro's libz.
#   - WANT_ZLIB intentionally undefined; libnx target sets `WANT_ZLIB=0`.
#   - HAVE_PHYSICAL_CDROM=0; we ship no physical CD reader on Switch.
#   - NDRC_THREAD=1 (matches upstream libnx defaults) -> async dynarec
#     compile thread.
#   - The libretro frontend is what foyer drives; no SDL / libpicofe /
#     in-game menu code is compiled.

# The aarch64 dynarec ships a .S file. CMake's "C CXX" project block has no
# ASM language enabled, so do it here on first include.
enable_language(ASM)

include(FetchContent)

FetchContent_Declare(libretro_pcsx_rearmed
    GIT_REPOSITORY https://github.com/libretro/pcsx_rearmed.git
    GIT_TAG        master
    GIT_SHALLOW    TRUE)
FetchContent_GetProperties(libretro_pcsx_rearmed)
if (NOT libretro_pcsx_rearmed_POPULATED)
    FetchContent_Populate(libretro_pcsx_rearmed)
endif()

set(_PCSX_DIR   ${libretro_pcsx_rearmed_SOURCE_DIR})
set(_PCSX_LPC   ${_PCSX_DIR}/libpcsxcore)
set(_PCSX_NDRC  ${_PCSX_LPC}/new_dynarec)
set(_PCSX_PLUG  ${_PCSX_DIR}/plugins)
set(_PCSX_FE    ${_PCSX_DIR}/frontend)
set(_PCSX_LRC   ${_PCSX_DIR}/deps/libretro-common)
set(_PCSX_LCHDR ${_PCSX_DIR}/deps/libchdr)
set(_PCSX_LZMA  ${_PCSX_LCHDR}/deps/lzma-24.05)
set(_PCSX_ZSTD  ${_PCSX_LCHDR}/deps/zstd-1.5.6/lib)

# ---------------------------------------------------------------------------
# include/revision.h is generated by upstream's Makefile from `git describe`.
# Synthesize a stub so frontend/main.c, frontend/menu.c, frontend/libretro.c,
# libpcsxcore/misc.c can include it. (We don't compile menu.c / main.c here
# but misc.c does pull it in.)
# ---------------------------------------------------------------------------
file(WRITE ${_PCSX_DIR}/include/revision.h
"#define REV \"foyer\"\n")

# ---------------------------------------------------------------------------
# libpcsxcore — the core PSX emulator (CPU, BIOS, DMA, MDEC, SPU, GPU API,
# CD-ROM, GTE).
# ---------------------------------------------------------------------------
set(_PCSX_CORE_SRC
    ${_PCSX_LPC}/cdriso.c
    ${_PCSX_LPC}/cdrom.c
    ${_PCSX_LPC}/cdrom-async.c
    ${_PCSX_LPC}/cheat.c
    ${_PCSX_LPC}/database.c
    ${_PCSX_LPC}/decode_xa.c
    ${_PCSX_LPC}/mdec.c
    ${_PCSX_LPC}/misc.c
    ${_PCSX_LPC}/plugins.c
    ${_PCSX_LPC}/ppf.c
    ${_PCSX_LPC}/psxbios.c
    ${_PCSX_LPC}/psxcommon.c
    ${_PCSX_LPC}/psxcounters.c
    ${_PCSX_LPC}/psxdma.c
    ${_PCSX_LPC}/psxhw.c
    ${_PCSX_LPC}/psxinterpreter.c
    ${_PCSX_LPC}/psxmem.c
    ${_PCSX_LPC}/psxevents.c
    ${_PCSX_LPC}/r3000a.c
    ${_PCSX_LPC}/sio.c
    ${_PCSX_LPC}/spu.c
    ${_PCSX_LPC}/gpu.c
    ${_PCSX_LPC}/pad.c
    ${_PCSX_LPC}/gte.c
    ${_PCSX_LPC}/gte_nf.c
    ${_PCSX_LPC}/gte_divider.c)

# gte_nf.c is normally built by re-compiling gte.c with -DFLAGLESS. Upstream
# gates this via a custom rule; we just compile gte_nf.c (which #includes
# gte.c with the right knob) the same way every other libnx port does.

# ---------------------------------------------------------------------------
# new_dynarec (ari64) — aarch64 backend.
# ---------------------------------------------------------------------------
set(_PCSX_DRC_SRC
    ${_PCSX_NDRC}/new_dynarec.c
    ${_PCSX_NDRC}/pcsxmem.c
    ${_PCSX_NDRC}/emu_if.c)

# linkage_arm64.S — small assembly trampoline used by the dynarec. Pass
# through gcc's assembler (uses .type / # immediates / etc).
set(_PCSX_DRC_ASM ${_PCSX_NDRC}/linkage_arm64.S)
set_source_files_properties(${_PCSX_DRC_ASM} PROPERTIES LANGUAGE ASM)

# ---------------------------------------------------------------------------
# SPU (dfsound) — the soft software synth.
# ---------------------------------------------------------------------------
set(_PCSX_SPU_SRC
    ${_PCSX_PLUG}/dfsound/dma.c
    ${_PCSX_PLUG}/dfsound/freeze.c
    ${_PCSX_PLUG}/dfsound/registers.c
    ${_PCSX_PLUG}/dfsound/spu.c
    ${_PCSX_PLUG}/dfsound/out.c
    ${_PCSX_PLUG}/dfsound/nullsnd.c)

# ---------------------------------------------------------------------------
# GPU — gpulib (the libretro-facing GPU plugin host) + gpu_neon (the
# upstream Exophase NEON GPU). For aarch64 we use psx_gpu_simd.c
# (NEON intrinsics) instead of the arm32-only psx_gpu_arm_neon.S.
# ---------------------------------------------------------------------------
set(_PCSX_GPU_SRC
    ${_PCSX_PLUG}/gpulib/gpu.c
    ${_PCSX_PLUG}/gpulib/vout_pl.c
    ${_PCSX_PLUG}/gpulib/prim.c
    ${_PCSX_PLUG}/gpulib/gpu_async.c
    ${_PCSX_PLUG}/gpu_neon/psx_gpu_if.c
    ${_PCSX_PLUG}/gpu_neon/psx_gpu/psx_gpu_simd.c)

# ---------------------------------------------------------------------------
# Color-space helpers (BGR<->RGB565 etc).
# ---------------------------------------------------------------------------
set(_PCSX_CSPACE_SRC ${_PCSX_FE}/cspace.c)

# ---------------------------------------------------------------------------
# Frontend — only the libretro entry points. No SDL, no libpicofe, no menu.
# main.c is gated with NO_FRONTEND so its `int main()` and the SDL/libpicofe
# bits (plat_finish, plat_get_root_dir, get_home_dir...) drop out — leaving
# only the helpers libretro.c needs (emu_core_preinit, SysReset, ...).
# ---------------------------------------------------------------------------
set(_PCSX_FE_SRC
    ${_PCSX_FE}/libretro.c
    ${_PCSX_FE}/main.c
    ${_PCSX_FE}/plugin.c
    ${_PCSX_FE}/pcsxr-threads.c)

# sysconf() is referenced from new_dynarec.c (via _SC_PAGESIZE). newlib
# declares it in <unistd.h> but doesn't ship an implementation — add the
# small lightrec sysconf shim that returns 4096 for _SC_PAGE_SIZE.
set(_PCSX_SYSCONF_SRC ${_PCSX_LPC}/lightrec/sysconf.c)

# ---------------------------------------------------------------------------
# Vendored libretro-common subset — enough for frontend/libretro.c +
# new_dynarec's features_cpu detection.
# ---------------------------------------------------------------------------
set(_PCSX_LRC_SRC
    ${_PCSX_LRC}/features/features_cpu.c)

# ---------------------------------------------------------------------------
# libchdr — CHD CD-ROM image reader. CHDs are common for PSX collections,
# so we keep this in even though it pulls a hefty zstd/lzma decoder.
# ---------------------------------------------------------------------------
set(_PCSX_CHDR_SRC
    ${_PCSX_LCHDR}/src/libchdr_bitstream.c
    ${_PCSX_LCHDR}/src/libchdr_cdrom.c
    ${_PCSX_LCHDR}/src/libchdr_chd.c
    ${_PCSX_LCHDR}/src/libchdr_flac.c
    ${_PCSX_LCHDR}/src/libchdr_huffman.c
    # LZMA (bundled, single-thread variant)
    ${_PCSX_LZMA}/src/Alloc.c
    ${_PCSX_LZMA}/src/CpuArch.c
    ${_PCSX_LZMA}/src/Delta.c
    ${_PCSX_LZMA}/src/LzFind.c
    ${_PCSX_LZMA}/src/LzmaDec.c
    ${_PCSX_LZMA}/src/LzmaEnc.c
    ${_PCSX_LZMA}/src/Sort.c
    # zstd (decompress only). The amd64 .S is x86 — skipped.
    ${_PCSX_ZSTD}/common/entropy_common.c
    ${_PCSX_ZSTD}/common/error_private.c
    ${_PCSX_ZSTD}/common/fse_decompress.c
    ${_PCSX_ZSTD}/common/xxhash.c
    ${_PCSX_ZSTD}/common/zstd_common.c
    ${_PCSX_ZSTD}/decompress/huf_decompress.c
    ${_PCSX_ZSTD}/decompress/zstd_ddict.c
    ${_PCSX_ZSTD}/decompress/zstd_decompress_block.c
    ${_PCSX_ZSTD}/decompress/zstd_decompress.c)

# ---------------------------------------------------------------------------
# Build the static library via the shared helper.
# ---------------------------------------------------------------------------
foyer_core_static_library(
    NAME pcsx_rearmed
    SOURCES
        ${_PCSX_CORE_SRC}
        ${_PCSX_DRC_SRC}
        ${_PCSX_DRC_ASM}
        ${_PCSX_SPU_SRC}
        ${_PCSX_GPU_SRC}
        ${_PCSX_CSPACE_SRC}
        ${_PCSX_FE_SRC}
        ${_PCSX_SYSCONF_SRC}
        ${_PCSX_LRC_SRC}
        ${_PCSX_CHDR_SRC}
    INCLUDE_DIRS
        # frontend/switch first so <sys/mman.h> resolves to the libnx shim,
        # not the win32-style include/mman/sys/mman.h.
        ${_PCSX_FE}/switch
        # libchdr's own include/ first so its FILE*-flavoured chd.h wins
        # over the libretro-common copy (which expects RFILE*; we don't
        # link USE_LIBRETRO_VFS in the libnx target).
        ${_PCSX_LCHDR}/include
        ${_PCSX_DIR}
        ${_PCSX_DIR}/include
        ${_PCSX_LPC}
        ${_PCSX_FE}
        ${_PCSX_LRC}/include
        ${_PCSX_LZMA}/include
        ${_PCSX_ZSTD}
    COMPILE_DEFS
        # libretro entry-point hooks
        __LIBRETRO__=1
        HAVE_LIBRETRO=1
        # libnx / Switch identification (Makefile.libretro: libnx target).
        SWITCH=1
        __SWITCH__=1
        HAVE_LIBNX=1
        NO_DYLIB=1
        # ari64 dynarec wants the full aarch64 ABI.
        __aarch64__=1
        __ARM_NEON__=1
        ARM=1
        # Endianness / inttypes.
        HAVE_INTTYPES=1
        HAVE_STDINT_H=1
        LSB_FIRST=1
        # Memory subsystems on libnx: no mmap, no posix_memalign. psxmem
        # falls back to calloc / aligned_alloc paths under these.
        P_HAVE_MMAP=0
        P_HAVE_POSIX_MEMALIGN=0
        DISABLE_MEM_LUTS=0
        # Builtin GPU = NEON (gpulib + gpu_neon, intrinsics path).
        GPU_NEON=1
        BUILTIN_GPU_NEON=1
        BUILTIN_GPU=neon
        # psx_gpu_if.c
        NEON_BUILD=1
        TEXTURE_CACHE_4BPP=1
        TEXTURE_CACHE_8BPP=1
        # SIMD intrinsics path of psx_gpu (not the ARM32-only .S).
        SIMD_BUILD=1
        # Async subsystems (Makefile.libretro libnx defaults).
        USE_ASYNC_CDROM=1
        USE_ASYNC_GPU=1
        USE_ASYNC_SPU=1
        # new_dynarec async compile thread.
        NDRC_THREAD=1
        HAVE_RTHREADS=1
        # libpcsxcore/cdriso.c gated paths.
        HAVE_CHD=1
        # No physical CD-ROM reader on Switch.
        # HAVE_CDROM intentionally undefined.
        # Frontend uses cspace.c's plain-C path; no NEON ASM helpers, so
        # leave HAVE_bgr555_to_rgb565 / HAVE_bgr888_to_x undefined — cspace.c
        # then provides its own C implementations.
        # zstd: we ship the decompress half only.
        ZSTD_DISABLE_ASM=1
        # LZMA tunables (libchdr's Makefile sets these when single-thread).
        Z7_ST=1
        # libretro-common in tree
        HAVE_THREADS=1
        # NO_FRONTEND drops `int main()`, plat_*() calls, and the SDL/
        # libpicofe paths inside frontend/main.c so only the helpers
        # libretro.c imports survive (emu_core_init, SysReset, etc.).
        NO_FRONTEND=1
        # NB: do NOT define INLINE globally — plugins/dfsound/stdafx.h
        # picks `INLINE=static inline` itself, and overriding it with
        # plain `inline` would leave INLINE-declared functions in spu.c
        # (interp_gauss_get, FModChangeFrequency, do_samples_adpcm, ...)
        # without external definitions and break the link.
        # libretro-common's headers fall back to retro_inline.h, which
        # defines INLINE = inline.
)

# Wire devkitPro's zlib to satisfy libchdr (it declares external `inflate`,
# `deflate`, `crc32`). pcsx_rearmed's libnx target sets WANT_ZLIB=0 and
# expects -lz to come from the platform.
if (TARGET ZLIB::ZLIB)
    target_link_libraries(core_pcsx_rearmed PUBLIC ZLIB::ZLIB)
endif()

# foyer_core_static_library() pins C_STANDARD=99. pcsx_rearmed is C-only,
# so leave it alone.
target_compile_options(core_pcsx_rearmed PRIVATE -w)
