# cores/swanstation.cmake — libretro-swanstation (PlayStation) core build.
#
# swanstation is the libretro fork of duckstation. Upstream's CMakeLists is
# tightly coupled to desktop OSes (mmap, shm_open, Vulkan/GL/D3D backends,
# ARM64 dynarec, etc.); none of that translates cleanly to a libnx homebrew
# binary. We mirror the source list here, swap out a handful of TUs that
# depend on virtual-memory tricks for libnx-friendly stubs, and force the
# software renderer.
#
# Trade-offs vs. desktop swanstation:
#   - Interpreter only (no MIPS recompiler) — significantly slower than
#     desktop, but functionally correct.
#   - Software GPU only (no GL/Vulkan/D3D) — keeps the hardware backends
#     out of the link entirely; hooks them up as no-op factories so the
#     libretro frontend still resolves the symbols.
#   - No fastmem (LUT/MMap fastmem both compiled out) — removes the page-
#     fault recovery requirement.
#   - No CHD support (libchdr pulls in zstd/lzma we don't ship) — bin/cue,
#     iso, img, pbp, ecm, mds, m3u still load.

include(FetchContent)

FetchContent_Declare(libretro_swanstation
    GIT_REPOSITORY https://github.com/libretro/swanstation.git
    GIT_TAG        main
    GIT_SHALLOW    TRUE
    SOURCE_SUBDIR  do-not-add-subdirectory)
FetchContent_MakeAvailable(libretro_swanstation)

set(_SWAN_DIR     ${libretro_swanstation_SOURCE_DIR})
set(_SWAN_SRC     ${_SWAN_DIR}/src)
set(_SWAN_DEP     ${_SWAN_DIR}/dep)
set(_SWAN_LRC     ${_SWAN_DEP}/libretro-common)
set(_SWAN_STUBS   ${CMAKE_CURRENT_LIST_DIR}/swanstation_stubs)

# ---------------------------------------------------------------------------
# version.h is normally generated by upstream's CMakeLists at configure time.
# We're not driving that, so synthesize a minimal one ourselves.
# ---------------------------------------------------------------------------
file(WRITE ${_SWAN_SRC}/libretro/version.h
"#pragma once
#define GIT_VERSION \"foyer\"
#define GIT_HASH \"foyer\"
#define BUILD_TIMESTAMP \"\"
")

# config.h is normally generated from src/config.h.cmake. byte_stream.cpp and
# file_system.cpp #include <config.h>; on libnx neither HAVE_MKSTEMP nor the
# alloca/malloc.h variants are wanted, so a hollow one suffices.
set(_SWAN_GENINC ${CMAKE_BINARY_DIR}/swanstation_gen)
file(MAKE_DIRECTORY ${_SWAN_GENINC})
file(WRITE ${_SWAN_GENINC}/config.h
"#pragma once
/* Intentionally empty — see cores/swanstation.cmake. */
")

# ---------------------------------------------------------------------------
# core/  — PSX emulator core (CPU, GPU sw, SPU, CDROM, DMA, GTE, etc.).
# Skip the recompiler TUs and the hardware GPU backends; the stubs file
# provides the missing factory symbols.
# ---------------------------------------------------------------------------
file(GLOB _SWAN_CORE_SRC ${_SWAN_SRC}/core/*.cpp)
list(FILTER _SWAN_CORE_SRC EXCLUDE REGEX
    "/(cpu_recompiler_[^/]+|gpu_hw_opengl|gpu_hw_vulkan|gpu_hw_d3d11|gpu_hw_d3d12|gpu_hw_shadergen|shadergen)\\.cpp$")

# ---------------------------------------------------------------------------
# common/ — utility code (file system, audio stream, CDimage, log, etc.).
# Drop the GL/Vulkan/D3D wrappers, the CHD reader (libchdr unavailable on
# Switch), and the platform-specific memory_arena / page_fault_handler /
# jit_code_buffer; the stubs replace them.
# ---------------------------------------------------------------------------
file(GLOB _SWAN_COMMON_SRC ${_SWAN_SRC}/common/*.cpp)
list(FILTER _SWAN_COMMON_SRC EXCLUDE REGEX
    "/(memory_arena|page_fault_handler|jit_code_buffer|cd_image_chd)\\.cpp$")

# ---------------------------------------------------------------------------
# libretro/ — the libretro entry points themselves. Compile all of them.
# ---------------------------------------------------------------------------
file(GLOB _SWAN_LR_SRC ${_SWAN_SRC}/libretro/*.cpp)

# ---------------------------------------------------------------------------
# Vendored libretro-common subset — enough for swanstation's includes
# (compat/strl.h, file/file_path.h, streams/file_stream.h, etc.).
# ---------------------------------------------------------------------------
set(_SWAN_LRC_SRC
    ${_SWAN_LRC}/compat/compat_posix_string.c
    ${_SWAN_LRC}/compat/compat_snprintf.c
    ${_SWAN_LRC}/compat/compat_strcasestr.c
    ${_SWAN_LRC}/compat/compat_strl.c
    ${_SWAN_LRC}/compat/fopen_utf8.c
    ${_SWAN_LRC}/encodings/encoding_utf.c
    ${_SWAN_LRC}/file/file_path.c
    ${_SWAN_LRC}/file/file_path_io.c
    ${_SWAN_LRC}/file/retro_dirent.c
    ${_SWAN_LRC}/lists/dir_list.c
    ${_SWAN_LRC}/lists/string_list.c
    ${_SWAN_LRC}/streams/file_stream.c
    ${_SWAN_LRC}/streams/file_stream_transforms.c
    ${_SWAN_LRC}/string/stdstring.c
    ${_SWAN_LRC}/time/rtime.c
    ${_SWAN_LRC}/vfs/vfs_implementation.c
)

# ---------------------------------------------------------------------------
# Vendored deps that are tiny and self-contained: stb_image (used by
# common/image.cpp), xxhash (system+texture hashing), miniz (PSF/PBP
# decompression).
# ---------------------------------------------------------------------------
set(_SWAN_VENDOR_SRC
    ${_SWAN_DEP}/stb/src/stb_image.c
    ${_SWAN_DEP}/stb/src/stb_image_resize.c
    ${_SWAN_DEP}/xxhash/src/xxhash.c
    ${_SWAN_DEP}/libchdr/deps/miniz-3.1.1/miniz.c
)

# ---------------------------------------------------------------------------
# Switch-specific stubs (replace the upstream TUs we filtered out).
# ---------------------------------------------------------------------------
set(_SWAN_STUB_SRC
    ${_SWAN_STUBS}/memory_arena.cpp
    ${_SWAN_STUBS}/page_fault_handler.cpp
    ${_SWAN_STUBS}/jit_code_buffer.cpp
    ${_SWAN_STUBS}/cd_image_chd.cpp
    ${_SWAN_STUBS}/gpu_hw_stubs.cpp
)

add_library(core_swanstation STATIC
    ${_SWAN_CORE_SRC}
    ${_SWAN_COMMON_SRC}
    ${_SWAN_LR_SRC}
    ${_SWAN_LRC_SRC}
    ${_SWAN_VENDOR_SRC}
    ${_SWAN_STUB_SRC}
)

# Header-search paths. _SWAN_STUBS comes first so our slim gpu_hw_opengl.h /
# gpu_hw_vulkan.h shadow the upstream headers (which include glad/vulkan).
# Generate a `core/` subdir of header shims in the build dir so that
# `#include "core/gpu_hw_opengl.h"` (used by libretro_host_interface.cpp)
# resolves to our slim stand-in header instead of the upstream one (which
# transitively includes glad / vulkan-loader / d3d). The shim dir is added
# to the include path *first* so it shadows ${_SWAN_SRC}.
set(_SWAN_SHIM ${_SWAN_GENINC}/shim)
file(MAKE_DIRECTORY ${_SWAN_SHIM}/core)
configure_file(${_SWAN_STUBS}/gpu_hw_opengl.h ${_SWAN_SHIM}/core/gpu_hw_opengl.h COPYONLY)
configure_file(${_SWAN_STUBS}/gpu_hw_vulkan.h ${_SWAN_SHIM}/core/gpu_hw_vulkan.h COPYONLY)

target_include_directories(core_swanstation PUBLIC
    ${_SWAN_SHIM}
    ${_SWAN_SRC}
    ${_SWAN_SRC}/libretro
    ${_SWAN_DEP}/stb/include
    ${_SWAN_DEP}/xxhash/include
    ${_SWAN_DEP}/libchdr/deps/miniz-3.1.1
    ${_SWAN_DEP}/openbios
    ${_SWAN_LRC}/include
    ${_SWAN_GENINC}
)

target_compile_definitions(core_swanstation PUBLIC
    __LIBRETRO__=1
    SWITCH=1
    __SWITCH__=1
    HAVE_LIBNX=1
    HAVE_STDINT_H=1
    # Tell libretro-common's memmap.h to skip <sys/mman.h> on Switch.
    INLINE=inline
)

target_compile_definitions(core_swanstation PRIVATE
    # Disable upstream subsystems that need host APIs we don't have.
    # WITH_RECOMPILER intentionally undefined  -> interpreter only.
    # WITH_MMAP_FASTMEM intentionally undefined -> LUT-only fastmem path,
    #                                              but bus.cpp still compiles
    #                                              with mmap path #ifdef'd out.
    # __LINUX__ and similar intentionally undefined.
    WANT_RAW_DATA_SECTOR=1
    WANT_SUBCODE=1
    VERIFY_BLOCK_CRC=1
)

# Silence the avalanche of unused-parameter / sign-compare / etc. warnings
# from upstream — none of them are actionable for us.
target_compile_options(core_swanstation PRIVATE -w)

set_target_properties(core_swanstation PROPERTIES
    CXX_STANDARD              17
    CXX_STANDARD_REQUIRED     ON
    C_STANDARD                99
    C_STANDARD_REQUIRED       ON
    POSITION_INDEPENDENT_CODE ON
)
